title: MoonDecimator
description: Personal site and Nostr identity page
theme: just-the-docs

url: https://moondecimator.github.io

nav_sort: case_insensitive
search_enabled: false

include:
  - .well-known
